### PR TITLE
clean up invoice file

### PR DESCRIPTION
**Pull request by hattonp**
i removed a bunch of stuff because the line item detail that was previously was tied to an invoice type that we aren't using. figured i would only keep what we needed and we can add as necessary, it's all pretty straightforward to do.

### CODE REVIEW

**Comment by PRAgarawal** [comment]
Was that code already there in the original library that we forked from? If so, I'm not sure why we need to delete it. Does it being there somehow make things difficult in the order-exporter code you're writing?

**Comment by hattonp** [comment]
I'm not sure why we need to keep a bunch of code we're never going to use either.

**Comment by hattonp** [comment]
i'll admit that i looked at it just didn't want to refactor the existing structure to work the way we 
need it to. i'm double checking... hang on. still stand by what i said earlier though.

**Comment by PRAgarawal** [comment]
The reason to keep it is that we're trying to keep open the possibility of merging this back to the original repo. Removing functionality without reason (or just because it suits us) is probably not something the original author/owner will be cool about.

**Pull request closed without merging**
